In [1]:
import os, sys, json, scipy
import numpy as np

In [15]:
mat = np.array([[2, 6], [1, 3], [3, 9], [5, 15]])
mat

array([[ 2,  6],
       [ 1,  3],
       [ 3,  9],
       [ 5, 15]])

In [16]:
eigenval, eigenvec = np.linalg.eig(np.matmul(mat.transpose(), mat))
eigenvec = eigenvec[np.argsort(eigenval)[::-1]]
eigenval = np.sort(eigenval)[::-1]
eigenval

array([390.,   0.])

In [17]:
eigenvec

array([[ 0.31622777, -0.9486833 ],
       [-0.9486833 , -0.31622777]])

In [19]:
svd_left = np.matmul(mat, eigenvec.transpose())
svd_left

array([[ -5.05964426,  -3.79473319],
       [ -2.52982213,  -1.8973666 ],
       [ -7.58946638,  -5.69209979],
       [-12.64911064,  -9.48683298]])

In [5]:
mat_shape = mat.shape

S = np.zeros(mat_shape)
for i in range(len(eigenval)):
    S[i][i] = np.sqrt(eigenval[i])

S

array([[19.74841766,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [6]:
UT = np.zeros((mat_shape[0], mat_shape[0]))
UT

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
for i in range(len(eigenval)):
    if eigenval[i] > 0:
        u = svd_left.transpose()[i] / S[i][i]
        UT[i] = u

UT

In [14]:
np.linalg.norm(svd_left.transpose()[0]) ** 2

249.6

In [12]:
6.324555 ** 2 + 3.162278 ** 2 + 9.486833 ** 2 + 15.81139 ** 2

390.000052199298